version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: userpoints-postgres
    environment:
      POSTGRES_USER: postgres          # istediğin kullanıcı
      POSTGRES_PASSWORD: postgres      # istediğin şifre
    ports:
      - "5432:5432"                    # host:container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
