spring:
  application:
    name: badge-service

  cloud:
    function:
      definition: actionCreatedConsumer

    stream:
      defaultBinder: kafka
      bindings:
        actionCreatedConsumer-in-0:
          destination: action-events
          group: badge-service
          content-type: application/json
          consumer:
            maxAttempts: 1   # Hata olursa tekrar denemesin -> direk DLQ


      kafka:
        bindings:
          actionCreatedConsumer-in-0:
            consumer:
              enableDlq: true   #Dead Letter Queue , service ��kmesini engelliyor ayr? bir topice kaydediyor
              dlqName: action-events-dlq
        binder:
          brokers: localhost:9094

  datasource:
    url: jdbc:postgresql://localhost:5435/badge_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
